controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_joint_trajectory_controller:
  ros__parameters:
    joints:
      - l_shoulder_swing_joint
      - l_shoulder_lateral_joint
      - l_elbow_joint
      - r_shoulder_swing_joint
      - r_shoulder_lateral_joint
      - r_elbow_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
