controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

leg_joint_trajectory_controller:
  ros__parameters:
    joints:
      - r_hip_twist_joint
      - r_hip_lateral_joint
      - r_hip_swing_joint
      - r_knee_joint
      - r_ankle_swing_joint
      - r_ankle_lateral_joint
      - l_hip_twist_joint
      - l_hip_lateral_joint
      - l_hip_swing_joint
      - l_knee_joint
      - l_ankle_swing_joint
      - l_ankle_lateral_joint
    allow_partial_joints: true
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
